# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f24a0e229afe2abc0d07a0c6603bf2a6e97c623ba8a1a0ed2cb98b93f17035a3f341d0298b7f20c5aba6930fc8f66478ad5f2d90b10002ede7146b874391db

test:
  secret_key_base: 33ef24c2db9fc466b3e1fb42d03c25b06f7bf176deff8ac2332d871e625ddac4a2f150b720a22517865af783c284a285b8997558a97d2d4fc105bb32da0d8bc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
